version: "3.9"
services:
  chat:
    container_name: chat-maker-chat-service
    build:
      context: .
      dockerfile: ./docker/chat_service/Dockerfile
    ports:
      - "8000:8000"
    hostname: chat-service
    environment:
      - STORAGE_TYPE=files
      - AUTH_SERVICE_URL=auth-service
      - AUTH_SERVICE_PORT=5000
      - USER_SERVICE_URL=user-service
      - USER_SERVICE_PORT=8080
      - CHAT_SERVICE_URL=chat-service
      - CHAT_SERVICE_PORT=8000
      - WS_SERVICE_URL=websocket-service
      - WS_SERVICE_PORT=5050
      - DATA_DIR=/data
      - ALLOW_ORIGINS=["*"]
  auth:
    container_name: chat-maker-auth-service
    build:
      context: .
      dockerfile: ./docker/auth_service/Dockerfile
    ports:
      - "5000:5000"
    hostname: auth-service
    environment:
      - STORAGE_TYPE=files
      - AUTH_SERVICE_URL=auth-service
      - AUTH_SERVICE_PORT=5000
      - USER_SERVICE_URL=user-service
      - USER_SERVICE_PORT=8080
      - CHAT_SERVICE_URL=chat-service
      - CHAT_SERVICE_PORT=8000
      - WS_SERVICE_URL=websocket-service
      - WS_SERVICE_PORT=5050
      - DATA_DIR=/data
      - ENCRYPTION_SECRET_KEY=16bytessecretkey
  user:
    container_name: chat-maker-user-service
    build:
      context: .
      dockerfile: ./docker/user_service/Dockerfile
    ports:
      - "8080:8080"
    hostname: user-service
    environment:
      - STORAGE_TYPE=files
      - AUTH_SERVICE_URL=auth-service
      - AUTH_SERVICE_PORT=5000
      - USER_SERVICE_URL=user-service
      - USER_SERVICE_PORT=8080
      - CHAT_SERVICE_URL=chat-service
      - CHAT_SERVICE_PORT=8000
      - WS_SERVICE_URL=websocket-service
      - WS_SERVICE_PORT=5050
      - DATA_DIR=/data
      - ALLOW_ORIGINS=["*"]
  websocket:
    container_name: chat-maker-websocket-service
    build:
      context: .
      dockerfile: ./docker/websocket_service/Dockerfile
    ports:
      - "5050:5050"
    hostname: websocket-service
    environment:
      - STORAGE_TYPE=files
      - AUTH_SERVICE_URL=auth-service
      - AUTH_SERVICE_PORT=5000
      - USER_SERVICE_URL=user-service
      - USER_SERVICE_PORT=8080
      - CHAT_SERVICE_URL=chat-service
      - CHAT_SERVICE_PORT=8000
      - WS_SERVICE_URL=websocket-service
      - WS_SERVICE_PORT=5050
      - DATA_DIR=/data
      - ALLOW_ORIGINS=["*"]
