apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chat-maker-websocket-service
  name: chat-maker-websocket-service
spec:
  ports:
  - nodePort: 32124
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chat-maker-websocket-service
  type: NodePort
status:
  loadBalancer: {}
