apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: chat-maker-chat-service
  name: chat-maker-chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-maker-chat-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chat-maker-chat-service
    spec:
      containers:
        - image: chat-service:local
          name: chat-maker-chat-service
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: AUTH_SERVICE_URL
              value: "0.0.0.0"
            - name: AUTH_SERVICE_PORT
              value: "80"
            - name: USER_SERVICE_URL
              value: "0.0.0.0"
            - name: USER_SERVICE_PORT
              value: "80"
            - name: CHAT_SERVICE_URL
              value: "0.0.0.0"
            - name: CHAT_SERVICE_PORT
              value: "80"
            - name: WS_SERVICE_URL
              value: "0.0.0.0"
            - name: WS_SERVICE_PORT
              value: "80"
            - name: STORAGE_TYPE
              value: "files"
            - name: DATA_DIR
              value: "/data"
            - name: ALLOW_ORIGINS
              value: '["*"]'
status: {}
